### ISSUE TITLE
the Console print "Hello World".

### ISSUE THREAD

**Issue by tan9p** [FireController1847/windows-folder-icon-maker#1]
So, you give me a "Hello World" ?!

**Comment by FireController1847** [comment]
what

**Comment by tan9p** [comment]
The project is almost empty 😊

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: FireController1847<mailto:notifications@github.com>
发送时间: 2020年2月6日 12:24
收件人: FireController1847/windows-folder-icon-maker<mailto:windows-folder-icon-maker@noreply.github.com>
抄送: Tang Yibo<mailto:tan9p@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [FireController1847/windows-folder-icon-maker] the Console print "Hello World". (#1)


what

**Comment by FireController1847** [comment]
Yes I have not completed work on the C# version. Check my GitLab (or, I think there's another GitHub mirroring that GitLab) for a Node.js version that (should) work
